var outbrain_dual_version="5.1.1.0",outbrain_dual_template_object=typeof outbrain_dual_template_object=="function"?outbrain_dual_template_object:function(o,p,q,r,s){var i=this;outbrain_dual_template_object.baseConstructor.call(this,o,p,q,r,s);this.imagesPreload=function(){};outbrain_template_manager.isAdMarking=true;this.adFieldsetId="outbrain_dual_ad_fs";this.adFieldsetClass="outbrain_dual_ad_class";this.adUlElementId="outbrain_dual_ad_ul";this.adUlClassDual="outbrain_dual_ad_ul_class";this.regUlClassDual=
"outbrain_dual_reg_ul_class";this.adWhatsThisId="outbrain_dual_ad_whats";this.dividerId="outbrain_dual_divider";this.adWhatsThisClass="outbrain_dual_ad_whats_class";this.adWhatsThisHrfClass="outbrain_dual_ad_whats_A_class";this.isAdRecOnTop=typeof OB_adMarkingOnTop=="boolean"?OB_adMarkingOnTop:false;this.checkRegRecFilter=function(){if(typeof OB_filter_reg_recs=="boolean"&&OB_filter_reg_recs==true)outbrain_settings.odb.odbGetDataUrlRec=outbrain_settings.odb.odbGetDataUrlRec.replace(outbrain_settings.keys_and_users.partnerKey,
"TURHTK3XYR")};this.checkRegRecFilter();this.buildDomDivider=function(){var a=[];a.push('<p id="'+this.dividerId+'_$INDEX_$POSITION" style="height:5px;margin:0px;padding:0px;display:none"></p>');return a.join("")};this.buildDomAdRecommendation=function(){var a=outbrain_browsers.ie&&outbrain_browsers.ie8Doc8?" outbrain_dual_ad_ul_ie8_class":"",b=[];b.push('<fieldset style="display:none;$FIELDSET_STYLE" id="'+this.adFieldsetId+'_$INDEX_$POSITION" class="$FIELDSET_CLASS '+this.adFieldsetClass+'" >');
b.push('    <legend class="$RECOMMENDATIONS_LEGEND_CLASS"></legend>');b.push('  \t<ul id="'+this.adUlElementId+'_$INDEX_$POSITION" class="'+this.adUlClassDual+' $RECOMMENDATIONS_UL_CLASS" '+a+">");b.push("  \t</ul>");b.push('    <div style="clear:both;" id="'+this.adWhatsThisId+'_$INDEX_$POSITION" class="'+this.adWhatsThisClass+' " ></div>');b.push("</fieldset>");return b.join("")};this.buildDomRecommendations=function(){var a=[];if(this.isAdRecOnTop==true){a.push(this.buildDomAdRecommendation("outbrain_dual_ul_ad_top"));
a.push(this.buildDomDivider())}a.push('<fieldset style="display:none;$FIELDSET_STYLE" id="$FIELDSET_ID_$INDEX_$POSITION" class="$FIELDSET_CLASS" >');a.push('      <div id="$RECOMMENDATIONS_WAIT_ID_outer_$INDEX" class="$RECOMMENDATIONS_WAIT_CLASS_outer" style="display:none;"><div class="$RECOMMENDATIONS_WAIT_CLASS_inner">');a.push('               <p><img style="border:0px !important"/></p>');a.push("       </div></div>");a.push('       <legend class="$RECOMMENDATIONS_LEGEND_CLASS"></legend>');a.push('  \t<ul id="$RECOMMENDATIONS_UL_ID_$INDEX_$POSITION" class="'+
this.regUlClassDual+' $RECOMMENDATIONS_UL_CLASS" style="display:block">');a.push("  \t</ul>");a.push("</fieldset>");a.push('<table id="$RECOMMENDATIONS_STATUS_ID_$INDEX_$POSITION" class="$RECOMMENDATIONS_STATUS_TABLE_CLASS" style="display:none;"><tr><td>');a.push('\t<div id="$RECOMMENDATIONS_PC_LEGEND_$INDEX_$POSITION" class="$RECOMMENDATIONS_PC_LEGENED_CLS" style="display:none;"></div>');a.push("</td><td>");a.push('\t<div id="$RECOMMENDATIONS_MORE_DIV_ID_$INDEX_$POSITION" class="$RECOMMENDATIONS_MORE_LINK_DIV_CLASS" style="display:none;"></div>');
a.push("</td></tr></table>");if(this.isAdRecOnTop!=true){a.push(this.buildDomDivider());a.push(this.buildDomAdRecommendation("outbrain_dual_ul_ad_bottom"))}return a.join("")};this.showRecommendations=function(a,b){var c=b.recTitle,e=b.jsonObj;c=this.changeStarsTextToImage(c,b.rankInfo.vote,true);if(!this.all_user_elements[this.positionRec])return false;if(this.recommendationsShowBefore(a))this.recommendationsLegendUpdate(a,c);else{var d=this.getElementWithFullName(this.constants.recommendationsUlId,
a);b=this.getElementWithFullName(this.adUlElementId,a);this.recommendationsLegendUpdate(a,c);var f=outbrain_template_manager.getRecommendationsPerDoc(outbrain_template_manager.DATA_REC_REGULAR_ONLY,e.response.documents.doc,null,null);c=outbrain_template_manager.getRecommendationsPerDoc(outbrain_template_manager.DATA_REC_AD_ONLY,e.response.documents.doc,null,null);var h=outbrain_template_manager.isAllSameSource(e.response.documents),g=typeof OB_filter_reg_recs=="boolean"&&OB_filter_reg_recs==true?
0:f.length,k=outbrain_settings.rater.recommendations.defaultRecNumber,l=k<=g?k:g;k=g-l;var m=c.length;if(g>0)OB_voterWidgetObjArray[a].SecLineOn=false;var n=d&&typeof d.opened=="boolean"&&d.opened==true;if(typeof OB_user_mode=="number"&&OB_user_mode==1){if(n)l=g;this.clearRecommendations(a,k)}for(var j=0;j<g;j++)this.renderOneRecommendation(a,d,f[j],j,h,j<l?true:false);for(d=0;d<m;d++){f=this.getCampType(a,e.response.documents);this.renderTitleAdRecommendation(a,b,d,e,f);this.renderOneRecommendation(a,
b,c[d],j,h,true)}this.showHideElementByIdName(this.constants.fieldsetId,a,g>0);this.showHideElementByIdName(this.dividerId,a,m>0&&g>0);this.setAdBoxPlace(a,m);this.checkIfMoreRecs(a,k,n);this.showHideRecsElements(a,e);this.enableBlogExternalElements(a);this.checkBottomTableWrapper(a)}};this.setAdBoxPlace=function(a,b){if((currElement=this.getElementWithFullName(this.adFieldsetId,a))&&currElement.style.display=="none")typeof OB_hook_id=="string"&&OB_hook_id.length>0&&b>0?this.hookAdsBox(OB_hook_id,
a):this.showHideElementByIdName(this.adFieldsetId,a,b>0)};this.recommendationsShowBefore=function(a){var b=false;b=this.getElementWithFullName(this.constants.fieldsetId,a);var c=this.getElementWithFullName(this.adFieldsetId,a);b=b?b.style.display!="none"||c.style.display!="none":false;if(b==true&&typeof OB_user_mode=="number"&&OB_user_mode==1){this.removeWaitClock(a);b=false}return b};this.showHideRecsElements=function(a,b){this.setAdLegend(a,b);if(currElement=this.getElementWithFullName(this.constants.rateStatusInfoTableId,
a))currElement.style.display="none";if(currElement=this.getElementWithFullName(this.constants.rateStatusInfoTdId,a))currElement.style.display="none";if(currElement=this.getElementWithFullName(this.constants.fieldsetId,a))OB_voterWidgetObjArray[a].hasRecommendations=true};this.renderTitleAdRecommendation=function(a,b,c,e,d){b=this.getpcName(a,e.response.documents);c="";c=d!=null&&d==2&&typeof outbrain_language_manager.getPiLegendText=="function"?outbrain_language_manager.getPiLegendText(i.languageName,
b)+":":outbrain_language_manager.getPcLegendText(i.languageName,b)+":";this.adsLegendUpdate(a,c);this.adsWhatsThisUpdate(a)};this.adsWhatsThisUpdate=function(a){var b=outbrain_language_manager.whatsThis(i.languageName),c='<a class="'+this.adWhatsThisHrfClass+'" href="javascript:void(0)" onClick="javascript:'+this.callForToolTip("this")+'" >[$AD_TEXT]</a>';c=c.replace(/\$AD_TEXT/g,b);(a=this.getElementWithFullName(this.adWhatsThisId,a))&&i.dom.setInnerHTML(a,c)};this.showHideElementByIdName=function(a,
b,c){if(a=this.getElementWithFullName(a,b))a.style.display=c?"block":"none"};this.adsLegendUpdate=function(a,b){if(a=this.getElementWithFullName(this.adFieldsetId,a))if((a=a.getElementsByTagName("legend")[0])&&a.innerHTML!=b){a.className=this.constants.recommendationsLegendClass;i.dom.setInnerHTML(a,b)}};this.createLinkOfPC=function(){return""};this.isSonOf=function(a,b){if(a&&a.childNodes.length>0&&b){a=a.childNodes;for(var c=0;c<a.length;c++)if(a[c].id==b.id)return true}return false};this.hookAdsBox=
function(a,b){var c=this.adFieldsetId+"_"+b+"_"+this.position,e=this.getElementWithFullName(this.constants.voterDivName,b);try{new outbrain_timeout(function(){if(document.getElementById(a+"_"+b))return true;return false},function(){var f=document.getElementById(a+"_"+b);if(f){var h=document.getElementById(c);if(h){if(!i.isSonOf(e,h)){h.style.display="block";return false}h.className+=outbrain_language_manager.isRtl(i.languageName)==true?" div-wrapper-right":" div-wrapper";var g=h.cloneNode(true);f.appendChild(g);
g.style.display="block";f.style.display="block";e.removeChild(h)}}},null,function(){var f=document.getElementById(c);if(f)f.style.display="block"},1E3,15,true)}catch(d){alert(d)}};this.resetTemplate=function(a){if(typeof OB_user_mode=="number"&&OB_user_mode==1){if(currElement=this.getElementWithFullName(this.adFieldsetId,a))currElement.style.display="none";if(currElement=this.getElementWithFullName(this.constants.fieldsetId,a))currElement.style.display="none";if(currElement=this.getElementWithFullName(this.constants.recommendationsPcLegendId,
a))currElement.style.display="none"}};this.clearRecommendations=function(a,b){var c=this.getElementWithFullName(this.adUlElementId,a);if(c!=null)c.innerHTML="";c=this.getElementWithFullName(this.constants.recommendationsUlId,a);if(c!=null)c.innerHTML="";a=this.getElementWithFullName(this.constants.recommendationsMoreDivId,a);if(a!=null&&b<1)a.innerHTML=""};this.callForToolTip=function(a){if(a!="this")a="'"+a+"'";var b="outbrain_template_manager.templates["+this.templateIndex+"].unTip();";b+="outbrain_template_manager.templates["+
this.templateIndex+"].tip("+a+",-358,378)";return b};this.tip=function(a,b,c){outbrain_rater.loadToolTip();try{var e=this.textForToolTip();new outbrain_timeout(function(){return typeof Tip=="function"},function(){Tip(e,BALLOON,true,ABOVE,true,FIX,[a,b,-7],EXCLUSIVE,true,BALLOONSTEMOFFSET,c)},null,null,20,1E3,true)}catch(d){return false}};this.showBalloon=false};outbrain_dual_template_object.prototype=outbrain_template_object;outbrain_dual_template_object.prototype.constructor=outbrain_dual_template_object;
outbrain_dual_template_object.baseConstructor=outbrain_template_object;outbrain_template_manager.addTemplate([["dual_template",outbrain_dual_template_object]]);
